export class CASH_VENDORS {
  public KEY_NO: number;
  public DFT_CODE: string;
  public VDR_CODE: string;
  public VDR_NAME: string;
  public BROKER_OP: string;
  public SUPPLIER_OP: string;
  public PAYEE_OP: string;
  public FIN_CUST_KEY: number;
  public COMMENTS: string;
  public STATUS: number;
  public IN_USER: string;
  public IN_DATE= new Date();
  public UP_USER: string;
  public UP_DATE= new Date();
  public OS_USER: string;
  public TERMINAL: string;
  public WEB_UID: string;
  public WEB_PASSWD: string;
  public CNTRY: string;
  public SRC_CODE: string;
  public ENTITY_OP: string;
  public OEM_OP: string;
  public SHIPYARD_OP: string;
  public PHONE_NO: string;
  public CELL_PHONE: string;
  public FAX: string;
  public EMAIL: string;
  public ADDRESS: string;
  public SRC_LINK: string;
  public APPR_STATUS: number;
  public VDR_ABBR: string;
  public PIC: string;
  public GLOBAL_OP: string;
  public AGENT_OP: string;
  public USR_CODE: string;
  public ALIAS_NAME: string;
  public YM_AGENT_OP: string;
  public BACKUP_OP: string;
  public MAIL_ADDR: string;
  public CAPITAL: number;
  public EMP_NUMS: number;
  public GENERAL_OP: string;
  public SYS_ID: string;
}
