export class OFFICE {
    public OFFICE_ID: number;     //
    public AGENT: string;     //
    public OFFICE1: string;     //
    public OFC_NAME: string;     //
    public DOC_SEQ: number;     //
    public TXM_SEQ: number;     //
    public REGION: string;     //
    public OFC_ROLE: string;     //
    public UP_OFFICE_ID: number;     //
    public BKREF_TG: string;     //
    public WEEK_SEQ: string;     //
    public SHPMNT_SEQ: number;     //
    public CITY_BASE: string;     //
    public ADDRESS: string;     //
    public TEL: string;     //
    public FAX: string;     //
    public EMAIL: string;     //
    public CTA_PERSON: string;     //
    public SALUTE: string;     //
    public TITLE: string;     //
    public CTA_DEPT: string;     //
    public IN_USER: string;     //
    public IN_DATE: Date;     //
    public UP_USER: string;     //
    public UP_DATE: Date;     //
    public TXMPORT: string;     //
    public ACTIVE: string;     //
    public WEB_INT: string;     //
    public REMARK: string;     //
    public ROLE: string;     //
    public URL: string;     //
    public RCC: string;     //
    public LCC: string;     //
    public TIMEZONE: string;     //
    public LOC_ADDRESS: string;     //
    public LOC_LANGUAGE: string;     //
    public LONGITUDE: string;     //
    public LATITUDE: string;     //
    public AgentOffice: string;     //
}
