export class USERS {
  public ESCAPE: string;
  public EMAIL_YN: string;
  public USER_ID: string;
  public USR_NAME: string;
  public PASSWORD: string;
  public DIVISION: string;
  public CNT_NO: string;
  public EXTEN_NO: string;
  public EMAIL: string;
  public SYS_MANAGER: string;
  public LOOP_CREATE: string;
  public OFC_MANAGER: string;
  public DIV_MANAGER: string;
  public IN_USER: string;
  public UP_USER: string;
  public LINE_CREATE: string;
  public DELETE_YN: string;
  public FAX_NO: string;
  public LAST_LOG_DATE: Date;
  public CHANGE_PASSWORD_DATE: Date;
  public IN_DATE: Date;
  public UP_DATE: Date;
  public USER_KEY: number;
  public OFFICE_ID: number;
  public CID: string;
  public token: string;
  public authenticationType: string;
}
